output error message for debugging

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -56,6 +56,12 @@ jobs:
         id: get-token
         run: |
           response=$(curl -X POST -d "grant_type=client_credentials&client_id=${{ secrets.CYPRESS_CLIENT_ID }}&client_secret=${{ secrets.CYPRESS_CLIENT_SECRET }}&scope=api://${{ secrets.CYPRESS_COMPLETEAPI_CLIENTID }}/.default" https://login.microsoftonline.com/${{ secrets.CYPRESS_TENANT_ID }}/oauth2/v2.0/token)
+          status=$(echo $response | jq -r .status)
+          if [ "$status" -ne 200 ]; then
+            error_message=$(echo $response | jq -r .error_description)
+            echo "Failed to get access token. Status: $status, Error: $error_message"
+            exit 1
+          fi
           access_token=$(echo $response | jq -r .access_token)
           echo "::set-output name=access_token::$access_token"
           echo $access_token > access_token.txt
